import { prisma } from "../src/lib/prisma.js";

const todos = [
  { id: 1, title: "Todo 1", completed: false },
  { id: 2, title: "Todo 2", completed: false },
  { id: 3, title: "Todo 3", description: "Description de la tâche 3", completed: false },
  { id: 4, title: "Todo 4", completed: true },
  { id: 5, title: "Todo 5", completed: false },
  { id: 6, title: "Todo 6", description: "Description de la tâche 6", completed: false },
  { id: 7, title: "Todo 7", completed: false },
  { id: 8, title: "Todo 8", completed: true },
  { id: 9, title: "Todo 9", description: "Description de la tâche 9", completed: false },
  { id: 10, title: "Todo 10", completed: false },
  { id: 11, title: "Todo 11", completed: false },
  { id: 12, title: "Todo 12", description: "Description de la tâche 12", completed: true },
  { id: 13, title: "Todo 13", completed: false },
  { id: 14, title: "Todo 14", completed: false },
  { id: 15, title: "Todo 15", description: "Description de la tâche 15", completed: false },
  { id: 16, title: "Todo 16", completed: true },
  { id: 17, title: "Todo 17", completed: false },
  { id: 18, title: "Todo 18", description: "Description de la tâche 18", completed: false },
  { id: 19, title: "Todo 19", completed: false },
  { id: 20, title: "Todo 20", completed: true },
  { id: 21, title: "Todo 21", description: "Description de la tâche 21", completed: false },
  { id: 22, title: "Todo 22", completed: false },
  { id: 23, title: "Todo 23", completed: false },
  { id: 24, title: "Todo 24", description: "Description de la tâche 24", completed: true },
  { id: 25, title: "Todo 25", completed: false },
  { id: 26, title: "Todo 26", completed: false },
  { id: 27, title: "Todo 27", description: "Description de la tâche 27", completed: false },
  { id: 28, title: "Todo 28", completed: true },
  { id: 29, title: "Todo 29", completed: false },
  { id: 30, title: "Todo 30", description: "Description de la tâche 30", completed: false },
  { id: 31, title: "Todo 31", completed: false },
  { id: 32, title: "Todo 32", completed: true },
  { id: 33, title: "Todo 33", description: "Description de la tâche 33", completed: false },
  { id: 34, title: "Todo 34", completed: false },
  { id: 35, title: "Todo 35", completed: false },
  { id: 36, title: "Todo 36", description: "Description de la tâche 36", completed: true },
  { id: 37, title: "Todo 37", completed: false },
  { id: 38, title: "Todo 38", completed: false },
  { id: 39, title: "Todo 39", description: "Description de la tâche 39", completed: false },
  { id: 40, title: "Todo 40", completed: true },
  { id: 41, title: "Todo 41", completed: false },
  { id: 42, title: "Todo 42", description: "Description de la tâche 42", completed: false },
  { id: 43, title: "Todo 43", completed: false },
  { id: 44, title: "Todo 44", completed: true },
  { id: 45, title: "Todo 45", description: "Description de la tâche 45", completed: false },
  { id: 46, title: "Todo 46", completed: false },
  { id: 47, title: "Todo 47", completed: false },
  { id: 48, title: "Todo 48", description: "Description de la tâche 48", completed: true },
  { id: 49, title: "Todo 49", completed: false },
  { id: 50, title: "Todo 50", completed: false },
  { id: 51, title: "Todo 51", description: "Description de la tâche 51", completed: false },
  { id: 52, title: "Todo 52", completed: true },
  { id: 53, title: "Todo 53", completed: false },
  { id: 54, title: "Todo 54", description: "Description de la tâche 54", completed: false },
  { id: 55, title: "Todo 55", completed: false },
  { id: 56, title: "Todo 56", completed: true },
  { id: 57, title: "Todo 57", description: "Description de la tâche 57", completed: false },
  { id: 58, title: "Todo 58", completed: false },
  { id: 59, title: "Todo 59", completed: false },
  { id: 60, title: "Todo 60", description: "Description de la tâche 60", completed: true },
  { id: 61, title: "Todo 61", completed: false },
  { id: 62, title: "Todo 62", completed: false },
  { id: 63, title: "Todo 63", description: "Description de la tâche 63", completed: false },
  { id: 64, title: "Todo 64", completed: true },
  { id: 65, title: "Todo 65", completed: false },
  { id: 66, title: "Todo 66", description: "Description de la tâche 66", completed: false },
  { id: 67, title: "Todo 67", completed: false },
  { id: 68, title: "Todo 68", completed: true },
  { id: 69, title: "Todo 69", description: "Description de la tâche 69", completed: false },
  { id: 70, title: "Todo 70", completed: false },
  { id: 71, title: "Todo 71", completed: false },
  { id: 72, title: "Todo 72", description: "Description de la tâche 72", completed: true },
  { id: 73, title: "Todo 73", completed: false },
  { id: 74, title: "Todo 74", completed: false },
  { id: 75, title: "Todo 75", description: "Description de la tâche 75", completed: false },
  { id: 76, title: "Todo 76", completed: true },
  { id: 77, title: "Todo 77", completed: false },
  { id: 78, title: "Todo 78", description: "Description de la tâche 78", completed: false },
  { id: 79, title: "Todo 79", completed: false },
  { id: 80, title: "Todo 80", completed: true },
  { id: 81, title: "Todo 81", description: "Description de la tâche 81", completed: false },
  { id: 82, title: "Todo 82", completed: false },
  { id: 83, title: "Todo 83", completed: false },
  { id: 84, title: "Todo 84", description: "Description de la tâche 84", completed: true },
  { id: 85, title: "Todo 85", completed: false },
  { id: 86, title: "Todo 86", completed: false },
  { id: 87, title: "Todo 87", description: "Description de la tâche 87", completed: false },
  { id: 88, title: "Todo 88", completed: true },
  { id: 89, title: "Todo 89", completed: false },
  { id: 90, title: "Todo 90", description: "Description de la tâche 90", completed: false },
  { id: 91, title: "Todo 91", completed: false },
  { id: 92, title: "Todo 92", completed: true },
  { id: 93, title: "Todo 93", description: "Description de la tâche 93", completed: false },
  { id: 94, title: "Todo 94", completed: false },
  { id: 95, title: "Todo 95", completed: false },
  { id: 96, title: "Todo 96", description: "Description de la tâche 96", completed: true },
  { id: 97, title: "Todo 97", completed: false },
  { id: 98, title: "Todo 98", completed: false },
  { id: 99, title: "Todo 99", description: "Description de la tâche 99", completed: false },
  { id: 100, title: "Todo 100", completed: true },
];

async function main() {
  await prisma.todo.createMany({ data: todos });
  console.log(`${todos.length} todos insérés avec succès.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
